//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderHeader
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Doc { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public string DocTotal { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Street { get; set; }
        public string Country { get; set; }
        public string ReferenceNumber { get; set; }
        public string OrderNum { get; set; }
        public string SalesPerson { get; set; }

        public virtual SalesOrderHeader SalesOrderHeader1 { get; set; }
        public virtual SalesOrderHeader SalesOrderHeader2 { get; set; }
        public virtual SalesOrderLine SalesOrderLine { get; set; }
    }
}
